name: CI
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: >
          --target=x86_64-unknown-linux-musl
          --verbose
          --release
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --target=x86_64-unknown-linux-musl
          --verbose
          --release
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v') && success()
      with:
        files: |
          target/x86_64-unknown-linux-musl/release/tpl
    - name: Login to DockerHub
      if: startsWith(github.ref, 'refs/tags/v') && success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: get tag
      if: startsWith(github.ref, 'refs/tags/v') && success()
      id: tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/refs\/tags\/v/, '');
    - name: Build and push
      if: startsWith(github.ref, 'refs/tags/v') && success()
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gottox/tpl:${{ steps.tag.outputs.result }}
